// Generated by CoffeeScript 1.7.1
module.exports = function(config) {
  return config.set({
    basePath: './specs',
    frameworks: ['mocha', 'chai'],
    preprocessors: {
      './../*.coffee': ['coffee'],
      '**/*.coffee': ['coffee']
    },
    files: [
      './../../dist/sea-debug.js', './../main.coffee', {
        pattern: './**/*.coffee',
        included: false
      }
    ],
    exclude: [],
    coffeePreprocessor: {
      options: {
        bare: true,
        sourceMap: false
      },
      transformPath: function(path) {
        return path.replace(/\.coffee$/, '.js');
      }
    },
    reporters: ['progress', 'spec'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_DEBUG,
    autoWatch: true,
    browsers: ['PhantomJS'],
    singleRun: false,
    plugins: ['karma-mocha', 'karma-mocha-reporter', 'karma-spec-reporter', 'karma-chai', 'karma-phantomjs-launcher', 'karma-coffee-preprocessor', 'karma-jade-preprocessor']
  });
};
